--[Part5-20] 댓글과 댓글수에 대한 처리

--REPLYCNT 속성 추가
ALTER TABLE TBL_BOARD ADD(REPLYCNT NUMBER DEFAULT 0);

-- 기존 댓글 replyCnt로 반영
UPDATE TBL_BOARD SET REPLYCNT = (
    SELECT COUNT(RNO) FROM TBL_REPLY
    WHERE TBL_REPLY.BNO = TBL_BOARD.BNO
    );
commit ;


SELECT COUNT(*) FROM TBL_BOARD;




