CREATE TABLE TBL_ATTACH(
    UUID        VARCHAR2(100) NOT NULL,
    UPLOADPATH  VARCHAR2(200) NOT NULL,
    FILENAME    VARCHAR2(100) NOT NULL,
    FILETYPE    CHAR(1) NOT NULL,
    BNO         NUMBER(10,0)
);


SELECT * FROM TBL_ATTACH;



ALTER TABLE TBL_ATTACH ADD CONSTRAINT PK_ATTACH PRIMARY KEY (UUID);

ALTER TABLE TBL_ATTACH ADD CONSTRAINT FK_BOARD_ATTACH FOREIGN KEY (BNO)
REFERENCES TBL_BOARD(BNO);

commit;


